### ISSUE TITLE
Design page "Tools & Data"

### ISSUE THREAD

**Issue by gplssm** [gplssm/egon-website#11]
Content is sketched by [tools+data.md](https://github.com/gplssm/egon-website/blob/dev/pages/tools%2Bdata.md) which includes [_tools.html](https://github.com/gplssm/egon-website/blob/dev/_includes/_tools.html) and [openego_data.html](https://github.com/gplssm/egon-website/blob/dev/_includes/openego_data.html). This is general a smart way using Jekyll and rather more using data files (`.yml`) and liquid.

### Tools

- Tool chain image will be replaced (without boarder)
- As example ding0 is already included as simple card. The length of description is represenative
- Buttons on the bottom indicate intended links. Guess you can make them look nicer easily :smile: 
- Liquid is use to loop through all tools defned in [tools.yml](https://github.com/gplssm/egon-website/blob/dev/_data/tools.yml)

### Data

- Again Liquid is used to loop over datasets
- Idea: use [pictograms of license features](https://meta.wikimedia.org/wiki/Open_Content_-_A_Practical_Guide_to_Using_Creative_Commons_Licences/The_Creative_Commons_licencing_scheme#/media/File:Open_Content_A_Practical_Guide_to_Using_Creative_Commons_Licences_web-28.png) (could be defined in `.yml`)

### Linking to OEDB

Somehow nicely link to the OEDB including the logo

**Comment by gplssm** [comment]
Similar as in #10, I emptied the page almost entirely and chose the same plain layout as for the start page. 
So again, simply write (most) of the HTML code in  [tools+data.md](https://github.com/gplssm/egon-website/blob/dev/pages/tools%2Bdata.md).
Two exceptions: I left the two includes ([_tools.html](https://github.com/gplssm/egon-website/blob/dev/_includes/_tools.html) and [openego_data.html](https://github.com/gplssm/egon-website/blob/dev/_includes/openego_data.html)) which parse the respective `.yml` files and insert its contents. Please implement the layout using the existing HTML code and data that is read by the liquid code

**Comment by bmlancien** [comment]
I'm designing the page right now. I think the page would look better if the open_ego tool chain image was re-designed to look more similar to the picture on the homepage at the top. But since this is not critical, I will first add the current image and we can see later if that is necessary to change it or not later.

**Comment by gplssm** [comment]
> I'm designing the page right now. I think the page would look better if the open_ego tool chain image was re-designed to look more similar to the picture on the homepage at the top. But since this is not critical, I will first add the current image and we can see later if that is necessary to change it or not later.

I agree with both, uniformly designed images are great. Postponing is prefered.

**Comment by bmlancien** [comment]
Here a mockup of the page. If you are okay with that I will work on that next week.

![egon_tools_data_sketch_v1](https://user-images.githubusercontent.com/33999424/80202846-88c96280-8626-11ea-9908-4b863b209672.png)

**Comment by gplssm** [comment]
Looks  good! Go for it!

Just two details
1. Personally, I would prefer left aligned text below the heading Tools and data. But if you have a preference for centered text, it's fine
2. I guess it would be possible to insert some text between the heading "our data" and the following table, right?

**Comment by bmlancien** [comment]
> Personally, I would prefer left aligned text below the heading Tools and data. But if you have a preference for centered text, it's fine

We can. It's just because the layout is more centered in general that I thought better to have that text centered too. But I can try to make it left-aligned.

> I guess it would be possible to insert some text between the heading "our data" and the following table, right?

Sure!
