### ISSUE TITLE
Design page "Partners"

### ISSUE THREAD

**Issue by gplssm** [gplssm/egon-website#22]
I added content to page "Partners", again in structured manner via parsing a `.yml` file. Please

- [ ] Adapt [_partners.html](https://github.com/gplssm/egon-website/blob/b4bd6a3c999449ab1378e4d97e6bf205cc930078/_includes/_partners.html) according to your needs to present partners
- [ ] Use [partners.md](https://github.com/gplssm/egon-website/blob/b4bd6a3c999449ab1378e4d97e6bf205cc930078/pages/partners.md) to add more styling/content (remember: you can use html in `.md` files)

**Comment by bmlancien** [comment]
@gplssm I was thinking of doing something like this:

![egon_tools_data_partners](https://user-images.githubusercontent.com/33999424/81293226-40219880-906d-11ea-919c-f86bef043bb2.png)

**Comment by gplssm** [comment]
Yes :star_struck: go for it!
