### ISSUE TITLE
Overall design

### ISSUE THREAD

**Issue by bmlancien** [gplssm/egon-website#32]
Check and update overall design once the main pages and components have been created

**Comment by gplssm** [comment]
Shall we do that, once we added real content and deployed the page to staging.ego-n.org? Then it would be like a final check-up

**Comment by bmlancien** [comment]
I think I can already start checking inconsitencies between pages now and then a second time with real content. I would just make a PR once I have finished checking real content though.

**Comment by gplssm** [comment]
:ok_hand: 
You can use dev. I merged all the PRs
