### ISSUE TITLE
Include project duration

### ISSUE THREAD

**Issue by IlkaCu** [gplssm/egon-website#56]
We did not include any information about the project duration yet. But this might be a helpful information for people visiting the egon-website. 
It could be added to the funding section.

**Comment by gplssm** [comment]
True! 

Shall we simply add it to the existing text like this?

This research project (FKZ: 03EI1002B) receives funding within the 7th Energy Research Programme by the German Federal Ministry for Economic Affairs and Energy from December 2019 until November 2022
